/*
 * Copyright (c) 2014 Anapass Co., Ltd.
 *              http://www.anapass.com/
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
 *
 * Alternatively, Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#include "MmpDefine.h"
#include "OMX_Video.h"
#include "OMX_Audio.h"
#include "omx_vendor_anapass.h"

static struct mmp_component_desc g_mmpcompdesc[] =
{
	{ MMP_FOURCC_VIDEO_MPEG4, OMX_COMPNAME_VIDEO_MPEG4_DECODER, OMX_MIMETYPE_VIDEO_MPEG4, MMP_FALSE, (MMP_U32)OMX_VIDEO_CodingMPEG4 },
    { MMP_FOURCC_VIDEO_MPEG2, OMX_COMPNAME_VIDEO_MPEG2_DECODER, OMX_MIMETYPE_VIDEO_MPEG2, MMP_FALSE, (MMP_U32)OMX_VIDEO_CodingMPEG2 },
    { MMP_FOURCC_VIDEO_H264,  OMX_COMPNAME_VIDEO_H264_DECODER,  OMX_MIMETYPE_VIDEO_AVC, MMP_FALSE, (MMP_U32)OMX_VIDEO_CodingAVC },
    { MMP_FOURCC_VIDEO_H263,  OMX_COMPNAME_VIDEO_H263_DECODER,  OMX_MIMETYPE_VIDEO_H263, MMP_FALSE, (MMP_U32)OMX_VIDEO_CodingH263 },
    { MMP_FOURCC_VIDEO_VC1,   OMX_COMPNAME_VIDEO_VC1_DECODER,   OMX_MIMETYPE_VIDEO_VC1, MMP_FALSE, (MMP_U32)OMX_VIDEO_CodingWMV },
    //{ MMP_FOURCC_VIDEO_WMV1,  OMX_COMPNAME_VIDEO_WMV1_DECODER,  OMX_MIMETYPE_VIDEO_WMV1, MMP_FALSE, (MMP_U32)OMX_VIDEO_CodingWMV },
    //{ MMP_FOURCC_VIDEO_WMV2,  OMX_COMPNAME_VIDEO_WMV2_DECODER,  OMX_MIMETYPE_VIDEO_WMV2, MMP_FALSE, (MMP_U32)OMX_VIDEO_CodingWMV },
    //{ MMP_FOURCC_VIDEO_WMV3,  OMX_COMPNAME_VIDEO_WMV3_DECODER,  OMX_MIMETYPE_VIDEO_WMV3, MMP_FALSE, (MMP_U32)OMX_VIDEO_CodingWMV },
    //{ MMP_FOURCC_VIDEO_VP6,   OMX_COMPNAME_VIDEO_VP6_DECODER,  OMX_MIMETYPE_VIDEO_VP6, MMP_FALSE, (MMP_U32)OMX_VIDEO_CodingVPX },
    //{ MMP_FOURCC_VIDEO_VP6F,  OMX_COMPNAME_VIDEO_VP6F_DECODER,  OMX_MIMETYPE_VIDEO_VP6F, MMP_FALSE, (MMP_U32)OMX_VIDEO_CodingVPX },
    //{ MMP_FOURCC_VIDEO_VP6A,  OMX_COMPNAME_VIDEO_VP6A_DECODER,  OMX_MIMETYPE_VIDEO_VP6A, MMP_FALSE, (MMP_U32)OMX_VIDEO_CodingVPX },
    //{ MMP_FOURCC_VIDEO_RV30,  OMX_COMPNAME_VIDEO_RV30_DECODER,  OMX_MIMETYPE_VIDEO_RV30, MMP_FALSE, (MMP_U32)OMX_VIDEO_CodingRV },
    //{ MMP_FOURCC_VIDEO_RV40,  OMX_COMPNAME_VIDEO_RV40_DECODER,  OMX_MIMETYPE_VIDEO_RV40, MMP_FALSE, (MMP_U32)OMX_VIDEO_CodingRV },
    //{ MMP_FOURCC_VIDEO_SVQ1,  OMX_COMPNAME_VIDEO_SVQ1_DECODER,  OMX_MIMETYPE_VIDEO_SVQ1, MMP_FALSE, (MMP_U32)OMX_VIDEO_CodingSVQ },
    //{ MMP_FOURCC_VIDEO_SVQ3,  OMX_COMPNAME_VIDEO_SVQ3_DECODER,  OMX_MIMETYPE_VIDEO_SVQ3, MMP_FALSE, (MMP_U32)OMX_VIDEO_CodingSVQ },
    { MMP_FOURCC_VIDEO_THEORA,  OMX_COMPNAME_VIDEO_THEORA_DECODER,  OMX_MIMETYPE_VIDEO_THEORA, MMP_FALSE, (MMP_U32)OMX_VIDEO_CodingTHEORA },
    { MMP_FOURCC_VIDEO_MJPEG,  OMX_COMPNAME_VIDEO_MJPEG_DECODER,  OMX_MIMETYPE_VIDEO_MJPEG, MMP_FALSE, (MMP_U32)OMX_VIDEO_CodingMJPEG },
    //{ MMP_FOURCC_VIDEO_MSMPEG4V1, OMX_COMPNAME_VIDEO_MSMPEG4V1_DECODER, OMX_MIMETYPE_VIDEO_MSMPEG4V1, OMX_FALSE, (MMP_U32)OMX_VIDEO_CodingMSMPEG },
    //{ MMP_FOURCC_VIDEO_MSMPEG4V2, OMX_COMPNAME_VIDEO_MSMPEG4V2_DECODER, OMX_MIMETYPE_VIDEO_MSMPEG4V2, OMX_FALSE, (MMP_U32)OMX_VIDEO_CodingMSMPEG },
    //{ MMP_FOURCC_VIDEO_MSMPEG4V3, OMX_COMPNAME_VIDEO_MSMPEG4V3_DECODER, OMX_MIMETYPE_VIDEO_MSMPEG4V3, OMX_FALSE, (MMP_U32)OMX_VIDEO_CodingMSMPEG },
    { MMP_FOURCC_VIDEO_FFMPEG,  OMX_COMPNAME_VIDEO_FFMPEG_DECODER,  OMX_MIMETYPE_VIDEO_FFMPEG, OMX_FALSE, (MMP_U32)OMX_VIDEO_CodingFFMpeg  },
    
	//{ MMP_COMP_ID_VDEC_H264, "OMX.anapass.h264.decoder",  "video/avc", MMP_FALSE },
    //{ MMP_COMP_ID_ADEC_AAC, "OMX.anapass.aac.decoder",  "audio/mp4a-latm", MMP_FALSE },

    { MMP_WAVE_FORMAT_MPEGLAYER3, OMX_COMPNAME_AUDIO_MP3_DECODER,   OMX_MIMETYPE_AUDIO_MP3, MMP_FALSE, (MMP_U32)OMX_AUDIO_CodingMP3 },
    { MMP_WAVE_FORMAT_MPEGLAYER2, OMX_COMPNAME_AUDIO_MP2_DECODER,   OMX_MIMETYPE_AUDIO_MP2, MMP_FALSE, (MMP_U32)OMX_AUDIO_CodingMP2 },
    { MMP_WAVE_FORMAT_MPEGLAYER1, OMX_COMPNAME_AUDIO_MP1_DECODER,   OMX_MIMETYPE_AUDIO_MP1, MMP_FALSE, (MMP_U32)OMX_AUDIO_CodingMP1 },
    //{ MMP_WAVE_FORMAT_WMA2,       OMX_COMPNAME_AUDIO_WMAV2_DECODER, OMX_MIMETYPE_AUDIO_WMAV2, MMP_FALSE, (MMP_U32)OMX_AUDIO_CodingWMA },
    { MMP_WAVE_FORMAT_AC3,        OMX_COMPNAME_AUDIO_AC3_DECODER, OMX_MIMETYPE_AUDIO_AC3, MMP_FALSE, (MMP_U32)OMX_AUDIO_CodingAC3 },
    { MMP_WAVE_FORMAT_AAC,        OMX_COMPNAME_AUDIO_AAC_DECODER, OMX_MIMETYPE_AUDIO_AAC_MAIN, MMP_FALSE, (MMP_U32)OMX_AUDIO_CodingAAC },
    { MMP_WAVE_FORMAT_AAC,        OMX_COMPNAME_AUDIO_AAC_DECODER, OMX_MIMETYPE_AUDIO_AAC, MMP_FALSE, (MMP_U32)OMX_AUDIO_CodingAAC },
    { MMP_WAVE_FORMAT_FLAC,       OMX_COMPNAME_AUDIO_FLAC_DECODER, OMX_MIMETYPE_AUDIO_FLAC, MMP_FALSE, (MMP_U32)OMX_AUDIO_CodingFLAC },
    { MMP_WAVE_FORMAT_ADPCM_MS,   OMX_COMPNAME_AUDIO_ADPCM_MS_DECODER, OMX_MIMETYPE_AUDIO_ADPCM_MS, MMP_FALSE, (MMP_U32)OMX_AUDIO_CodingADPCM },
    { MMP_WAVE_FORMAT_FFMPEG,     OMX_COMPNAME_AUDIO_FFMPEG_DECODER, OMX_MIMETYPE_AUDIO_FFMPEG, MMP_FALSE, (MMP_U32)OMX_AUDIO_CodingADPCM },
    
    //{ MMP_COMP_ID_ADEC_FFMPEG, "FfmpegAudioDecoder",  "audio/ffmpeg", MMP_FALSE },
    //{ MMP_COMP_ID_VDEC_FFMPEG, "FfmpegVideoDecoder",  "video/ffmpeg", MMP_FALSE },
};

struct mmp_component_desc* get_omx_desc(int index) {
    
    int sz;
    struct mmp_component_desc* p_desc = NULL;

    sz = sizeof(g_mmpcompdesc)/sizeof(g_mmpcompdesc[0]);
    if(index < sz) {
        p_desc = &g_mmpcompdesc[index];
    }

    return p_desc;
}