#ifndef __REGS_ISP_H__
#define __REGS_ISP_H__

//#include <linux/sizes.h>
//#include <mach/irqs-gdm7243v.h>

/*****************************************************************************/

#if 0
#define GDM_DXO_BASE                (0xED100000)
#define GDM_DXO_SIZE                (SZ_256K)

#define GDM_ISP_BASE                (0xED140000)
#define GDM_ISP_SIZE                (SZ_64K)

#define GDM_SIF_BASE                (0xED350000)
#define GDM_SIF_SIZE                (SZ_8K)

#define GDM_ISP_IRQ0                (IRQ_ISP0)
#define GDM_ISP_IRQ1                (IRQ_ISP1)
#endif  /*0*/

/*****************************************************************************/

// ISP Main
#define REG_ISP_SEL_VSENSOR                     (0x0000)
#define REG_ISP_SEL_BT601                       (0x0004)
#define REG_ISP_BLK_CLOCKEN                     (0x0010)
#define REG_ISP_BLK_SWRESET                     (0x0014)
#define REG_ISP_SW_INTERRUPT                    (0x00F0)
#define REG_ISP_PRODUCT_VER                     (0x00F4)
#define REG_ISP_PRODUCT_REV                     (0x00F8)
#define REG_ISP_PRODUCT_DATE                    (0x00FC)
#define REG_ISP_INTR_IRQ0_EDGE                  (0x0100)
#define REG_ISP_INTR_IRQ0_POLA                  (0x0104)
#define REG_ISP_INTR_IRQ0_MASK                  (0x0108)
#define REG_ISP_INTR_IRQ0_PEND                  (0x010C)
#define REG_ISP_INTR_IRQ1_EDGE                  (0x0110)
#define REG_ISP_INTR_IRQ1_POLA                  (0x0114)
#define REG_ISP_INTR_IRQ1_MASK                  (0x0118)
#define REG_ISP_INTR_IRQ1_PEND                  (0x011C)

// Interrupt Sources - IRQ0
#define GISP_IRQ0_W_DX_INTERRUPT                (1 << 0)
#define GISP_IRQ0_W_PSTM_SENSORIN_RST           (1 << 1)
#define GISP_IRQ0_W_PSTM_CAPTURE_RST            (1 << 2)
#define GISP_IRQ0_W_PSTM_VIDEO_RST              (1 << 3)
#define GISP_IRQ0_W_PSTM_DISPLAY_RST            (1 << 4)
#define GISP_IRQ0_W_PSTM_FDETECT_RST            (1 << 5)
#define GISP_IRQ0_W_VS_INTERRUPT0               (1 << 6)
#define GISP_IRQ0_W_VS_INTERRUPT1               (1 << 7)
#define GISP_IRQ0_W_BT_INTERRUPT0               (1 << 8)
#define GISP_IRQ0_W_BT_INTERRUPT1               (1 << 9)
#define GISP_IRQ0_I_SENSOR_IF_INTR0             (1 << 10)
#define GISP_IRQ0_I_SENSOR_IF_INTR1             (1 << 11)
#define GISP_IRQ0_W_SENSOR_SOF                  (1 << 12)
#define GISP_IRQ0_W_SENSOR_EOL                  (1 << 13)
#define GISP_IRQ0_W_SENSOR_EOF                  (1 << 14)
#define GISP_IRQ0_W_FS_INTERRUPT                (1 << 15)

// Interrupt Sources - IRQ1
#define GISP_IRQ1_WD_CAP_DONE                   (1 << 0)
#define GISP_IRQ1_WD_VID_DONE                   (1 << 1)
#define GISP_IRQ1_WD_DIS_DONE                   (1 << 2)
#define GISP_IRQ1_WD_FD_DONE                    (1 << 3)
#define GISP_IRQ1_IC_RD_DONE                    (1 << 4)
#define GISP_IRQ1_IC_WR_DONE                    (1 << 5)
#define GISP_IRQ1_VS_VSYNC_START                (1 << 6)
#define GISP_IRQ1_VS_TRANS_DONE                 (1 << 7)
#define GISP_IRQ1_BT_VSYNC_START                (1 << 8)
#define GISP_IRQ1_BT_TRANS_DONE                 (1 << 9)
#define GISP_IRQ1_I_SENSOR_IF_INTR0             (1 << 10)
#define GISP_IRQ1_I_SENSOR_IF_INTR1             (1 << 11)
#define GISP_IRQ1_W_SENSOR_SOF                  (1 << 12)
#define GISP_IRQ1_W_SENSOR_EOL                  (1 << 13)
#define GISP_IRQ1_W_SENSOR_EOF                  (1 << 14)
#define GISP_IRQ1_W_SW_INTERRUPT                (1 << 15)

/*****************************************************************************/

// ISP WDMA
#define OFF_ISP_WD_CONTROL              (0x00)
#define OFF_ISP_WD_IMG_TYPE             (0x04)
#define OFF_ISP_WD_IMG_SIZE             (0x08)
#define OFF_ISP_WD_IMG_STRIDE           (0x0C)
#define OFF_ISP_WD_BASE_YADDR           (0x10)
#define OFF_ISP_WD_BASE_UADDR           (0x14)
#define OFF_ISP_WD_BASE_VADDR           (0x18)
#define OFF_ISP_WD_FUNCTION0            (0x20)
#define OFF_ISP_WD_FUNCTION1            (0x24)
#define OFF_ISP_WD_FUNCTION2            (0x28)
#define OFF_ISP_WD_FUNCTION3            (0x2C)
#define OFF_ISP_WD_FUNCTION4            (0x30)
#define OFF_ISP_WD_DEBUG0               (0x40)

// Capture
#define REG_ISP_WD_CP_BASE              (0x3100)
#define REG_ISP_WD_CP_CONTROL           (REG_ISP_WD_CP_BASE+OFF_ISP_WD_CONTROL)
#define REG_ISP_WD_CP_IMG_TYPE          (REG_ISP_WD_CP_BASE+OFF_ISP_WD_IMG_TYPE)
#define REG_ISP_WD_CP_IMG_SIZE          (REG_ISP_WD_CP_BASE+OFF_ISP_WD_IMG_SIZE)
#define REG_ISP_WD_CP_IMG_STRIDE        (REG_ISP_WD_CP_BASE+OFF_ISP_WD_IMG_STRIDE)
#define REG_ISP_WD_CP_BASE_YADDR        (REG_ISP_WD_CP_BASE+OFF_ISP_WD_BASE_YADDR)
#define REG_ISP_WD_CP_BASE_UADDR        (REG_ISP_WD_CP_BASE+OFF_ISP_WD_BASE_UADDR)
#define REG_ISP_WD_CP_BASE_VADDR        (REG_ISP_WD_CP_BASE+OFF_ISP_WD_BASE_VADDR)
#define REG_ISP_WD_CP_FUNCTION0         (REG_ISP_WD_CP_BASE+OFF_ISP_WD_FUNCTION0)
#define REG_ISP_WD_CP_FUNCTION1         (REG_ISP_WD_CP_BASE+OFF_ISP_WD_FUNCTION1)
#define REG_ISP_WD_CP_FUNCTION2         (REG_ISP_WD_CP_BASE+OFF_ISP_WD_FUNCTION2)
#define REG_ISP_WD_CP_FUNCTION3         (REG_ISP_WD_CP_BASE+OFF_ISP_WD_FUNCTION3)
#define REG_ISP_WD_CP_FUNCTION4         (REG_ISP_WD_CP_BASE+OFF_ISP_WD_FUNCTION4)
#define REG_ISP_WD_CP_DEBUG0            (REG_ISP_WD_CP_BASE+OFF_ISP_WD_DEBUG0)

// Video
#define REG_ISP_WD_VD_BASE              (0x3200)
#define REG_ISP_WD_VD_CONTROL           (REG_ISP_WD_VD_BASE+OFF_ISP_WD_CONTROL)
#define REG_ISP_WD_VD_IMG_TYPE          (REG_ISP_WD_VD_BASE+OFF_ISP_WD_IMG_TYPE)
#define REG_ISP_WD_VD_IMG_SIZE          (REG_ISP_WD_VD_BASE+OFF_ISP_WD_IMG_SIZE)
#define REG_ISP_WD_VD_IMG_STRIDE        (REG_ISP_WD_VD_BASE+OFF_ISP_WD_IMG_STRIDE)
#define REG_ISP_WD_VD_BASE_YADDR        (REG_ISP_WD_VD_BASE+OFF_ISP_WD_BASE_YADDR)
#define REG_ISP_WD_VD_BASE_UADDR        (REG_ISP_WD_VD_BASE+OFF_ISP_WD_BASE_UADDR)
#define REG_ISP_WD_VD_BASE_VADDR        (REG_ISP_WD_VD_BASE+OFF_ISP_WD_BASE_VADDR)
#define REG_ISP_WD_VD_FUNCTION0         (REG_ISP_WD_VD_BASE+OFF_ISP_WD_FUNCTION0)
#define REG_ISP_WD_VD_FUNCTION1         (REG_ISP_WD_VD_BASE+OFF_ISP_WD_FUNCTION1)
#define REG_ISP_WD_VD_FUNCTION2         (REG_ISP_WD_VD_BASE+OFF_ISP_WD_FUNCTION2)
#define REG_ISP_WD_VD_FUNCTION3         (REG_ISP_WD_VD_BASE+OFF_ISP_WD_FUNCTION3)
#define REG_ISP_WD_VD_FUNCTION4         (REG_ISP_WD_VD_BASE+OFF_ISP_WD_FUNCTION4)
#define REG_ISP_WD_VD_DEBUG0            (REG_ISP_WD_VD_BASE+OFF_ISP_WD_DEBUG0)

// Display
#define REG_ISP_WD_DP_BASE              (0x3300)
#define REG_ISP_WD_DP_CONTROL           (REG_ISP_WD_DP_BASE+OFF_ISP_WD_CONTROL)
#define REG_ISP_WD_DP_IMG_TYPE          (REG_ISP_WD_DP_BASE+OFF_ISP_WD_IMG_TYPE)
#define REG_ISP_WD_DP_IMG_SIZE          (REG_ISP_WD_DP_BASE+OFF_ISP_WD_IMG_SIZE)
#define REG_ISP_WD_DP_IMG_STRIDE        (REG_ISP_WD_DP_BASE+OFF_ISP_WD_IMG_STRIDE)
#define REG_ISP_WD_DP_BASE_YADDR        (REG_ISP_WD_DP_BASE+OFF_ISP_WD_BASE_YADDR)
#define REG_ISP_WD_DP_BASE_UADDR        (REG_ISP_WD_DP_BASE+OFF_ISP_WD_BASE_UADDR)
#define REG_ISP_WD_DP_BASE_VADDR        (REG_ISP_WD_DP_BASE+OFF_ISP_WD_BASE_VADDR)
#define REG_ISP_WD_DP_FUNCTION0         (REG_ISP_WD_DP_BASE+OFF_ISP_WD_FUNCTION0)
#define REG_ISP_WD_DP_FUNCTION1         (REG_ISP_WD_DP_BASE+OFF_ISP_WD_FUNCTION1)
#define REG_ISP_WD_DP_FUNCTION2         (REG_ISP_WD_DP_BASE+OFF_ISP_WD_FUNCTION2)
#define REG_ISP_WD_DP_FUNCTION3         (REG_ISP_WD_DP_BASE+OFF_ISP_WD_FUNCTION3)
#define REG_ISP_WD_DP_FUNCTION4         (REG_ISP_WD_DP_BASE+OFF_ISP_WD_FUNCTION4)
#define REG_ISP_WD_DP_DEBUG0            (REG_ISP_WD_DP_BASE+OFF_ISP_WD_DEBUG0)

// Face Detect
#define REG_ISP_WD_FD_BASE              (0x3400)
#define REG_ISP_WD_FD_CONTROL           (REG_ISP_WD_FD_BASE+OFF_ISP_WD_CONTROL)
#define REG_ISP_WD_FD_IMG_TYPE          (REG_ISP_WD_FD_BASE+OFF_ISP_WD_IMG_TYPE)
#define REG_ISP_WD_FD_IMG_SIZE          (REG_ISP_WD_FD_BASE+OFF_ISP_WD_IMG_SIZE)
#define REG_ISP_WD_FD_IMG_STRIDE        (REG_ISP_WD_FD_BASE+OFF_ISP_WD_IMG_STRIDE)
#define REG_ISP_WD_FD_BASE_YADDR        (REG_ISP_WD_FD_BASE+OFF_ISP_WD_BASE_YADDR)
#define REG_ISP_WD_FD_BASE_UADDR        (REG_ISP_WD_FD_BASE+OFF_ISP_WD_BASE_UADDR)
#define REG_ISP_WD_FD_BASE_VADDR        (REG_ISP_WD_FD_BASE+OFF_ISP_WD_BASE_VADDR)
#define REG_ISP_WD_FD_FUNCTION0         (REG_ISP_WD_FD_BASE+OFF_ISP_WD_FUNCTION0)
#define REG_ISP_WD_FD_FUNCTION1         (REG_ISP_WD_FD_BASE+OFF_ISP_WD_FUNCTION1)
#define REG_ISP_WD_FD_FUNCTION2         (REG_ISP_WD_FD_BASE+OFF_ISP_WD_FUNCTION2)
#define REG_ISP_WD_FD_FUNCTION3         (REG_ISP_WD_FD_BASE+OFF_ISP_WD_FUNCTION3)
#define REG_ISP_WD_FD_FUNCTION4         (REG_ISP_WD_FD_BASE+OFF_ISP_WD_FUNCTION4)
#define REG_ISP_WD_FD_DEBUG0            (REG_ISP_WD_FD_BASE+OFF_ISP_WD_DEBUG0)

// ISP_WD_*_CONTROL Mask
#define GISP_WD_CONTROL_START           (0x00000001)
#define GISP_WD_CONTROL_DONE            (0x00000002)
#define GISP_WD_CONTROL_CLEAR           (0x00000004)
#define GISP_WD_CONTROL_AUTOSTART       (0x00000010)
#define GISP_WD_CONTROL_BURST_SIZE      (0x00000F00)
#define GISP_WD_CONTROL_YSTATUS         (0x000F0000)
#define GISP_WD_CONTROL_CSTATUS         (0x00F00000)

/*****************************************************************************/

// ISP_VS
#define REG_ISP_VS_CONTROL              (0x1000)
#define REG_ISP_VS_IMG_SIZE             (0x1004)
#define REG_ISP_VS_BASE_ADDR            (0x1008)
#define REG_ISP_VS_BIN_NUM              (0x100C)
#define REG_ISP_VS_STATUS               (0x1010)

// ISP_BT
#define REG_ISP_BT_CONTROL              (0x2000)
#define REG_ISP_BT_SIG_MODE             (0x2004)
#define REG_ISP_BT_IMG_SIZE             (0x2008)
#define REG_ISP_BT_STATUS               (0x200C)
#define REG_ISP_BT_VBLK_CNT             (0x2010)
#define REG_ISP_BT_VACT_CNT             (0x2014)
#define REG_ISP_BT_HBLK_CNT             (0x2018)

/*****************************************************************************/

// SIF
#define REG_SIF_BT601                               (0x0004)
#define REG_SIF_SEL_SENSOR                          (0x0008)
#define REG_SIF_FPGA_CON                            (0x0010)
#define REG_SIF_FPGA_CLOCK                          (0x0014)
#define REG_SIF_CONT_SENSOR                         (0x0020)
#define REG_SIF_SYNC_POINT                          (0x0024)
#define REG_SIF_RST_LINE_ERR                        (0x0028)
#define REG_SIF_LINE_COUNT                          (0x002C)
#define REG_SIF_CNT_LINE_ERR                        (0x0030)
#define REG_SIF_LINE_COUNT_DXO                      (0x0034)
#define REG_SIF_CNT_LINE_ERR_DXO                    (0x0038)

#define REG_SIF_MCL4_HOST_VERSION_OS                (0x0200)
#define REG_SIF_MCL4_HOST_N_LANES_OS                (0x0204)
#define REG_SIF_MCL4_HOST_CSI2_RESETN_OS            (0x0208)
#define REG_SIF_MCL4_HOST_INT_ST_MAIN_OS            (0x020C)
#define REG_SIF_MCL4_HOST_DATA_IDS_1_OS             (0x0210)
#define REG_SIF_MCL4_HOST_PHY_SHUTDOWNZ_OS          (0x0240)
#define REG_SIF_MCL4_HOST_DPHY_RSTZ_OS              (0x0244)
#define REG_SIF_MCL4_HOST_PHY_RX_OS                 (0x0248)
#define REG_SIF_MCL4_HOST_PHY_STOPSTATE_OS          (0x024C)
#define REG_SIF_MCL4_HOST_PHY_TEST_CTRL0_OS         (0x0250)
#define REG_SIF_MCL4_HOST_PHY_TEST_CTRL1_OS         (0x0254)
#define REG_SIF_MCL4_HOST_INT_ST_PHY_FATAL_OS       (0x02E0)
#define REG_SIF_MCL4_HOST_INT_MSK_PHY_FATAL_OS      (0x02E4)
#define REG_SIF_MCL4_HOST_INT_FORCE_PHY_FATAL_OS    (0x02E8)
#define REG_SIF_MCL4_HOST_INT_ST_PKT_FATAL_OS       (0x02F0)
#define REG_SIF_MCL4_HOST_INT_MSK_PKT_FATAL_OS      (0x02F4)
#define REG_SIF_MCL4_HOST_INT_FORCE_PKT_FATAL_OS    (0x02F8)
#define REG_SIF_MCL4_HOST_INT_ST_FRAME_FATAL_OS     (0x0300)
#define REG_SIF_MCL4_HOST_INT_MSK_FRAME_FATAL_OS    (0x0304)
#define REG_SIF_MCL4_HOST_INT_FORCE_FRAME_FATAL_OS  (0x0308)
#define REG_SIF_MCL4_HOST_INT_ST_PHY_OS             (0x0310)
#define REG_SIF_MCL4_HOST_INT_MSK_PHY_OS            (0x0314)
#define REG_SIF_MCL4_HOST_INT_FORCE_PHY_OS          (0x0318)
#define REG_SIF_MCL4_HOST_INT_ST_PKT_OS             (0x0320)
#define REG_SIF_MCL4_HOST_INT_MSK_PKT_OS            (0x0324)
#define REG_SIF_MCL4_HOST_INT_FORCE_PKT_OS          (0x0328)
#define REG_SIF_MCL4_HOST_INT_ST_LINE_OS            (0x0330)
#define REG_SIF_MCL4_HOST_INT_MSK_LINE_OS           (0x0334)
#define REG_SIF_MCL4_HOST_INT_FORCE_LINE_OS         (0x0338)

#define REG_SIF_MIF4_IMAGE_SIZE                     (0x0404)
#define REG_SIF_MIF4_SENSOR_OUT_BIT                 (0x040C)
#define REG_SIF_MIF4_VSYNC_POINT                    (0x0410)
#define REG_SIF_MIF4_VSYNC_FRM_NUM                  (0x0414)
#define REG_SIF_MIF4_CONT                           (0x0418)
#define REG_SIF_MIF4_DEBUG_DATA                     (0x0420)
#define REG_SIF_MIF4_W_P_CNT                        (0x0430)
#define REG_SIF_MIF4_CONT2                          (0x0434)

#define REG_SIF_MCL2_HOST_VERSION_OS                (0x0600)
#define REG_SIF_MCL2_HOST_N_LANES_OS                (0x0604)
#define REG_SIF_MCL2_HOST_CSI6_RESETN_OS            (0x0608)
#define REG_SIF_MCL2_HOST_INT_ST_MAIN_OS            (0x060C)
#define REG_SIF_MCL2_HOST_DATA_IDS_1_OS             (0x0610)
#define REG_SIF_MCL2_HOST_PHY_SHUTDOWNZ_OS          (0x0640)
#define REG_SIF_MCL2_HOST_DPHY_RSTZ_OS              (0x0644)
#define REG_SIF_MCL2_HOST_PHY_RX_OS                 (0x0648)
#define REG_SIF_MCL2_HOST_PHY_STOPSTATE_OS          (0x064C)
#define REG_SIF_MCL2_HOST_PHY_TEST_CTRL0_OS         (0x0650)
#define REG_SIF_MCL2_HOST_PHY_TEST_CTRL1_OS         (0x0654)
#define REG_SIF_MCL2_HOST_INT_ST_PHY_FATAL_OS       (0x06E0)
#define REG_SIF_MCL2_HOST_INT_MSK_PHY_FATAL_OS      (0x06E4)
#define REG_SIF_MCL2_HOST_INT_FORCE_PHY_FATAL_OS    (0x06E8)
#define REG_SIF_MCL2_HOST_INT_ST_PKT_FATAL_OS       (0x06F0)
#define REG_SIF_MCL2_HOST_INT_MSK_PKT_FATAL_OS      (0x06F4)
#define REG_SIF_MCL2_HOST_INT_FORCE_PKT_FATAL_OS    (0x06F8)
#define REG_SIF_MCL2_HOST_INT_ST_FRAME_FATAL_OS     (0x0700)
#define REG_SIF_MCL2_HOST_INT_MSK_FRAME_FATAL_OS    (0x0704)
#define REG_SIF_MCL2_HOST_INT_FORCE_FRAME_FATAL_OS  (0x0708)
#define REG_SIF_MCL2_HOST_INT_ST_PHY_OS             (0x0710)
#define REG_SIF_MCL2_HOST_INT_MSK_PHY_OS            (0x0714)
#define REG_SIF_MCL2_HOST_INT_FORCE_PHY_OS          (0x0718)
#define REG_SIF_MCL2_HOST_INT_ST_PKT_OS             (0x0720)
#define REG_SIF_MCL2_HOST_INT_MSK_PKT_OS            (0x0724)
#define REG_SIF_MCL2_HOST_INT_FORCE_PKT_OS          (0x0728)
#define REG_SIF_MCL2_HOST_INT_ST_LINE_OS            (0x0730)
#define REG_SIF_MCL2_HOST_INT_MSK_LINE_OS           (0x0734)
#define REG_SIF_MCL2_HOST_INT_FORCE_LINE_OS         (0x0738)

#define REG_SIF_MIF2_IMAGE_SIZE                     (0x0804)
#define REG_SIF_MIF2_SENSOR_OUT_BIT                 (0x080C)
#define REG_SIF_MIF2_VSYNC_POINT                    (0x0810)
#define REG_SIF_MIF2_VSYNC_FRM_NUM                  (0x0814)
#define REG_SIF_MIF2_CONT                           (0x0818)
#define REG_SIF_MIF2_DEBUG_DATA                     (0x0820)
#define REG_SIF_MIF2_W_P_CNT                        (0x0830)
#define REG_SIF_MIF2_CONT2                          (0x0834)

//#define REG_SIF_PAR_SENSOR_SELECT                   (0x0A00)
#define REG_SIF_PAR_SENSOR_INVERT                   (0x0A04)
#define REG_SIF_PAR_SENSOR_DELAY                    (0x0A08)
#define REG_SIF_PAR_SENSOR_OUT_BIT                  (0x0A0C)
#define REG_SIF_PAR_VSYNC_POINT                     (0x0A10)
#define REG_SIF_PAR_VSYNC_FRM_NUM                   (0x0A14)
#define REG_SIF_PAR_IMAGE_SIZE                      (0x0A20)
#define REG_SIF_PAR_ENB_BYPASS                      (0x0A30)
#define REG_SIF_PAR_DEBUG_DATA                      (0x0A34)

/*****************************************************************************/

#endif  /*__REGS_ISP_H__*/
